export const ROLES = {
  CUSTOMER: "CUSTOMER",
  SHOPKEEPER: "SHOPKEEPER",
  DELIVERY_AGENT: "DELIVERY_AGENT",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN"
};

export const PUBLIC_REGISTRATION_ROLES = [
  ROLES.CUSTOMER,
  ROLES.SHOPKEEPER,
  ROLES.DELIVERY_AGENT
];
